# Change these first
owner: empreendercacb # Your GitHub organization or username, where this repository lives
repo: monitor # The name of this repository

sites:
  - name: "Portal Empreender - Produção"
    url: https://www.empreender.org.br/sistema/
  - name: "Portal Empreender - Teste versão PHP"
    url: https://teste.cacbempreenderapp.org.br/sistema
  - name: "Portal Empreender - Teste Beta"
    url: http://beta.cacbempreenderapp.org.br/
  - name: "API V5 - Teste Beta"
    url: https://api.cacbempreenderapp.org.br/
    

    
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Monitor do Portal Empreender
  introTitle: "**Portal Empreender**"
  introMessage: "O Monitor do Portal Empreender monitora os serviços da CACB."
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://cacb.org.br/
